default: help

NAME = scrape_mal

PYTHON = python3
PIP = pip3

VENV_BIN = venv/bin
VENV_PIP = $(VENV_BIN)/$(PIP)
VENV_PYTHON = $(VENV_BIN)/$(PYTHON)

clean:
	- rm -rf venv dist build .coverage
	- find . -depth -name \*\.egg-info -exec rm -rf {} \;
	- find .  -depth -name \*\.pyc -exec rm -rf {} \;
	- find .  -depth -name __pycache__ -exec rm -rf {} \;

dev: clean
	$(PYTHON) -m venv venv
	$(VENV_PYTHON) -m ensurepip --upgrade
	$(VENV_PIP) install -r requirements.txt

help:
	@echo "Choose one of the following targets:"
	@echo " * dev - Create a virtual environment"
	@echo " * clean - Remove any files and directories generated by development"
	@echo " * help - Show this message"
