AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: An AWS Serverless Specification template describing your function.
Resources:
  insertAnimeRecord:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: insert_anime_record.handler
      Runtime: python3.6
      CodeUri: .
      Description: ""
      MemorySize: 128
      Timeout: 30
      Role: "arn:aws:iam::944713421596:role/LambdaRDSFullAccess"
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /insertAnimeRecord
            Method: ANY
      Environment:
        Variables:
          PG_HOST: XXXX
          PG_USERNAME: XXXX
          PG_PASSWORD: XXXX
          PG_DATABASE: XXXX
